#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         CDB_File
version:      0.94
version_from: CDB_File.pm
installdirs:  site
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
